PRAGMA foreign_keys = ON;

CREATE TABLE UserAccount(
  UserAccountID INTEGER PRIMARY KEY AUTOINCREMENT,
  Email TEXT UNIQUE NOT NULL,
  PasswordHash TEXT NOT NULL,
  IsActive INTEGER NOT NULL DEFAULT 1,
  CreatedAt TEXT NOT NULL,
  LastLoginAt TEXT NOT NULL
);

CREATE TABLE "Role"(
  RoleID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Description TEXT
);

CREATE TABLE Customer(
  CustomerID INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  BirthDate TEXT NOT NULL,
  Phone TEXT UNIQUE NOT NULL,
  Street TEXT NOT NULL,
  Postal TEXT NOT NULL,
  City TEXT NOT NULL,
  Status TEXT NOT NULL,
  fk_RoleID INTEGER NOT NULL,
  fk_UserAccountID INTEGER NOT NULL,
  FOREIGN KEY(fk_RoleID) REFERENCES "Role"(RoleID),
  FOREIGN KEY(fk_UserAccountID) REFERENCES UserAccount(UserAccountID)
);

CREATE TABLE Employee(
  EmployeeID INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Email TEXT UNIQUE NOT NULL,
  JobTitle TEXT NOT NULL,
  HireDate TEXT NOT NULL,
  IsActive INTEGER NOT NULL DEFAULT 1,
  fk_RoleID INTEGER NOT NULL,
  FOREIGN KEY(fk_RoleID) REFERENCES "Role"(RoleID)
);

CREATE TABLE AccountType(
  AccountTypeID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Currency TEXT NOT NULL,
  MonthlyFee INTEGER NOT NULL
);

CREATE TABLE Account(
  AccountID INTEGER PRIMARY KEY AUTOINCREMENT,
  IBAN TEXT UNIQUE NOT NULL,
  Balance NUMERIC NOT NULL,
  Status TEXT NOT NULL,
  OpenedAt TEXT NOT NULL,
  ClosedAt TEXT,
  fk_AccountType INTEGER NOT NULL,
  FOREIGN KEY(fk_AccountType) REFERENCES AccountType(AccountTypeID)
);

CREATE TABLE Card(
  CardID INTEGER PRIMARY KEY AUTOINCREMENT,
  CardType TEXT NOT NULL,
  ExpiryDate TEXT NOT NULL,
  Status TEXT NOT NULL,
  DailyLimit INTEGER,
  fk_AccountID INTEGER NOT NULL,
  FOREIGN KEY(fk_AccountID) REFERENCES Account(AccountID)
);

CREATE TABLE TransactionType(
  TransactionTypeID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Direction TEXT NOT NULL,
  Description TEXT
);

CREATE TABLE "Transaction"(
  TransactionID INTEGER PRIMARY KEY AUTOINCREMENT,
  BookingDate TEXT NOT NULL,
  Description TEXT,
  fk_AccountID INTEGER NOT NULL,
  fk_TransactionType INTEGER NOT NULL,
  FOREIGN KEY(fk_AccountID) REFERENCES Account(AccountID),
  FOREIGN KEY(fk_TransactionType) REFERENCES TransactionType(TransactionTypeID)
);

CREATE TABLE CustomerAccount(
  CustomerAccountID INTEGER PRIMARY KEY AUTOINCREMENT,
  fk_CustomerID INTEGER NOT NULL,
  fk_AccountID INTEGER NOT NULL,
  FOREIGN KEY(fk_CustomerID) REFERENCES Customer(CustomerID),
  FOREIGN KEY(fk_AccountID) REFERENCES Account(AccountID)
);
